# Generated by Django 3.2.15 on 2022-09-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220921_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='readings',
            field=models.TextField(null=True),
        ),
    ]
