# Generated by Django 3.2.15 on 2022-09-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220921_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(default=0),
        ),
    ]
