# Generated by Django 3.2.15 on 2022-09-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_session_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
